import "./styles/global.scss";
import "./styles/index.css";
import {Poppins} from "next/font/google"

export const metadata = {
  title: "Personal Portfolio",
  description: "Generated by create next app",
};

const Poppins_font= Poppins({
  subsets:['latin'],
  weight:['100','200','300','400','500','600','700'],
  display:'swap'
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={Poppins_font.className}>{children}</body>
    </html>
  );
}
